### ISSUE TITLE
https://components.espressif.com/components/zorxx/rtci2c description is incorrect

### ISSUE THREAD

**Issue by pebender** [zorxx/rtci2c#1]
The assertion that this library supports ds3231 is incorrect.

**Comment by zorxx** [comment]
There is no such "assertion"

**Comment by pebender** [comment]
Did you look at the page? The subheading reads: "Real-time clock driver (rtc, i2c, ds1307, ds1302, pcf8563, ds3231, date)".

https://components.espressif.com/components/zorxx/rtci2c/versions/1.1.1

**Comment by zorxx** [comment]
https://github.com/zorxx/rtci2c/blob/83bbe1f12de80ec9e5e02f7263c91c0739f2c832/include/rtci2c.h#L36

**Comment by pebender** [comment]
I have seen that. That was my confirmation that it does not support ds3231 when I tried to use it for ds3231 as claimed in the description at https://components.espressif.com. Why do you insist on not reading or correcting the description at https://components.espressif.com/components/zorxx/rtci2c/versions/1.1.1 ?
