### ISSUE TITLE
Cannot use while using u8g2 library

### ISSUE THREAD

**Issue by YengaJaf-Aizatron** [zorxx/rtci2c#2]
The RTC initialisation fails when using the [u8g2 library by mkfrey](https://github.com/mkfrey/u8g2-hal-esp-idf). The serial monitor shows the following:

```
E (1091) i2c.common: I2C bus id(0) has already been acquired
E (1091) i2c.common: acquire bus failed
E (1101) i2c.master: i2c_new_master_bus(857): I2C bus acquire failed
E (1111) i2c.common: i2c_release_bus_handle(154): Bus not freed entirely
E (1121) NTP_SYNC: RTC initialization failed
```

This is my init function where the last error comes from:
```
void init_rtc(void) {
    i2c_lowlevel_config config = {0};
    config.port = ESP_I2C_PORT;
    config.pin_sda = ESP_I2C_SDA;
    config.pin_scl = ESP_I2C_SCL;

    rtc_ctx = rtci2c_init(RTCI2C_DEVICE_DS1307, DEVICE_I2C_ADDRESS, &config);
    if (rtc_ctx == NULL) {
        ESP_LOGE(TAG, "RTC initialization failed");
    } else {
        ESP_LOGI(TAG, "RTC initialized successfully");
    }
}
```

Is this a issue with the u8g2 library, or with this RTC library?

**Comment by zorxx** [comment]
It appears the u8g2 library is configuring and opening the same I2C bus that you've specified for rtci2c. The rtci2c library allows the use of i2c buses that have been configured by other (non-rtci2c) means through the use of the 'i2c_master_bus_handle_t *bus' parameter in the i2c_lowlevel_config structure (passed as the third argument to the rtci2c_init function). As long as you can get a pointer to the i2c_master_bus_handle_t that has been configured previously by the u8g2 library, rtci2c can make use of it. If the u8g2 library doesn't allow access to the i2c bus it has configured, the only recourse is to use a different physical i2c bus for your RTC device.

**Comment by YengaJaf-Aizatron** [comment]
Solved. Changed the u8g2 i2c_master_bus_handle_t i2c_bus_handle to global, and then passed it to the RTC initialiser
